### ISSUE TITLE
Legacy pyreadline issue and PR check list

### ISSUE THREAD

**Issue by eabase** [pyreadline3/pyreadline3#5]
Here are all the currently open PR's and issues from `pyreadline` repo.  

Please use this list to check off the items that have been fixed **here**. 
If you do check it off, and if it's not too much to ask, please comment with the PR that fixed it.

---

- [ ]  [77]  `UnicodeDecodeError` after using sympy's math expressions?
- [ ]  [76]  Anyone interested in making an unofficial maintained branch of this?
- [ ]  [75]  Fix for variable assignment issue in keysyms mod
- [ ]  [74]  Code error in pyreadline/keysyms/__init__.py
- [ ]  [73]  python.exe on Windows 10 with Python 3.10 errors after this module is installed
- [ ]  [72]  Fix Python 3.10 AtributeError
- [ ]  [71]  input color not working on windows(10)[19042]
- [ ]  [70]  AttributeError: module 'readline' has no attribute 'redisplay'
- [ ]  [69]  Remove deprecation warning
- [ ]  [68]  Fix deprecation warning
- [x]  [67]  BUG: fix regex to avoid DoS
- [ ]  [65]  collections deprecation warning (potential incompatibility with Python 3.9)
- [x]  [64]  Press <Tab> at the beginning of the line
- [ ]  [62]  [UnicodeDecodeError] - UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 321: illegal multibyte sequence
- [x]  [61]  #54 UnicodeDecodeError
- [ ]  [60]  Open history file with utf-8 encoding, fix #55 on Python 3 too
- [ ]  [59]  module 'pyreadline' has no attribute 'parse_and_bind'
- [ ]  [58]  Project status?
- [ ]  [57]  Open history file with utf-8 encoding, fix #55
- [ ]  [56]  Fix redisplay() missing & history-files with non-latin chars
- [ ]  [55]  Reading history file fails with non-latin chars on Windows
- [ ]  [54]  .python_history file decoding error when it has non-ascii char
- [ ]  [53]  TypeError: unsupported operand type(s) for *: 'ReadLineTextBuffer' and 'int'
- [ ]  [52]  AttributeError: module 'pyreadline.console' has no attribute 'Console'
- [ ]  [51]  Implement readline.redisplay(), fixing #49
- [ ]  [50]  Fix typo
- [ ]  [49]  AttributeError: module 'readline' has no attribute 'redisplay'
- [x]  [48]  Make it possible to use colored completions
- [ ]  [46]  windows 10(ver 1607) cmd.exe ansi color text not work.
- [ ]  [45]  No behavior for arbitrary input autocomplete set-up
- [x]  [44]  switch to setup tools
- [ ]  [43]  Parse and bind editing mode
- [ ]  [42]  Uninstall readline hook on exception -- **`OUTDATED`**
- [ ]  [41]  v2.1 changes missing from github
- [ ]  [40]  pyreadline==2.1 install fails using pip
- [ ]  [39]  Slow pasting of code into default Python interpreter
- [ ]  [38]  Python 3.5 support
- [ ]  [37]  Wrong cursor position when entering Unicode
- [ ]  [34]  Non incremental search fails on python 3
- [ ]  [33]  AttributeError: 'module' object has no attribute 'logger'
- [ ]  [31]  Multi-line input is displayed incorrectly
- [ ]  [30]  Incorrect encoding of history files
- [ ]  [29]  vi-mode and swedish characters
- [x]  [28]  Fixed typo and docstring line length
- [ ]  [27]  ~~Fix Ctrl-R and Ctrl-S prompt that does not accept space character as par...~~ -- **`Still Relevant?`**
- [ ]  [26]  ~~Change behavior of return key in the interactive search.~~ -- **`NOT Relevant`**
- [ ]  [24]  :o: Isolate kernel32 DLL usage.                                                      -- **`Probably Good Idea!`**
- [ ]  [23]  selection commands don't work with ipython/cygwin
- [ ]  [22]  Current build confuses py2exe; conflict with console module
- [ ]  [20]  ~~Update eggsetup.py~~ **`DEPRECATED`**
- [ ]  [19]  ~~Update setup.py~~ **`DEPRECATED`**
- [ ]  [17]  :o: Missing readline methods implemented
- [ ]  [16]  correct name of python dll in case of debug python interpreter
- [ ]  [15]  Modified rlmain.py to make saving the prompt position an option that is
- [ ]  [14]  Cannot import pyreadline when username is not ascii
- [ ]  [12]  Correction to README
- [ ]  [8]   resurrect ironpython support
- [ ]  [5]   ironpython support is broken

**Comment by eabase** [comment]
BTW. If you wonder how to get a list like that above, I use the [`gh-missue`](https://github.com/E3V3A/gh-missue) tool. It can batch copy issues and labels from any github repo, as well as list open or closed issues, separately. I've used it for years, and it was recently updated to better support the new github API. However, I suggest to first try it on a separate test repo, as it will just dump issues into the target repo, without any questions asked. (And you can't delete issues, once created!)

But to keep things fresh here, I think it's a good idea to **not** copy anything from the old repo.

**Comment by eabase** [comment]
**Legacy PRs:**

- [ ] #75  Fix for variable assignment issue in keysyms mod                           
- [ ] #72  Fix Python 3.10 AtributeError                                              
- [ ] #69  Remove deprecation warning                                                 
- [ ] #68  Fix deprecation warning                                                    
- [ ] #67  BUG: fix regex to avoid DoS                                                
- [ ] #61  #54 UnicodeDecodeError                                                     
- [ ] #60  Open history file with utf-8 encoding, fix #55 on Python 3 too             
- [ ] #57  Open history file with utf-8 encoding, fix #55                             
- [ ] #56  Fix redisplay() missing & history-files with non-latin chars               
- [ ] #51  Implement readline.redisplay(), fixing #49                                 
- [ ] #50  Fix typo                                                                   
- [ ] #48  Make it possible to use colored completions                                
- [ ] #44  switch to setup tools                                                      
- [ ] #42  Uninstall readline hook on exception                                       
- [ ] #28  Fixed typo and docstring line length                                       
- [ ] #27  Fix Ctrl-R and Ctrl-S prompt that does not accept space character as par...
- [ ] #26  Change behavior of return key in the interactive search.                   
- [ ] #24  Isolate kernel32 DLL usage.                                                
- [ ] #20  Update eggsetup.py                                                         
- [ ] #19  Update setup.py                                                            
- [ ] #17  Missing readline methods implemented                                       
- [ ] #16  correct name of python dll in case of debug python interpreter             
- [ ] #15  Modified rlmain.py to make saving the prompt position an option that is    
- [ ] #12  Correction to README                                                       
- [ ] #8   resurrect ironpython support
